@host = localhost:3000

### salúdame
GET http://{{host}}/api/hi

### obtener la representación romana de un número
POST http://{{host}}/api/toRoman
content-type: application/json

{
  "numero": 99,
  "veces" : 5
}

### obtener el número de veces que aparece un carácter en el quijote.txt
GET http://{{host}}/api/cuentaLetrasQuijote/e


